title: WindowsSSD-Script
description: Extend the lifetime of your SSD unit on Windows
theme: jekyll-theme-tactile
show_downloads: true
github:
  zip_url: https://github.com/equilaterus/WindowsSSD-Script/releases/latest
