title: WindowsSSD-Script
description: Powershell scripts to automate symbolic link generation for SSD units on Windows.
theme: jekyll-theme-tactile
show_downloads: true
github:
  zip_url: https://github.com/equilaterus/WindowsSSD-Script/releases/latest
